[settings]
nSteps = 10
t_start = 0.0
t_end = 1.0

[geometry]
filepath = "meshes/bay.msh"
fish_area = [[0.0, 0.45], [0.0, 0.2]]
initial_oil_area = [0.35, 0.45]

[IO]
logName = "logfile"
writeFrequency = 5
restartFile = "input/solution.txt"
